'use client';
import { useAppState } from '../components/AppState';

export default function AdminPage() {
  const { predictions, admin, setAdmin } = useAppState();
  const winnerGoals = [...predictions].sort((a,b)=>Math.abs(a.totalGoals-admin.actualGoals)-Math.abs(b.totalGoals-admin.actualGoals)||a.submittedAt.localeCompare(b.submittedAt))[0];
  const winnerCards = [...predictions].sort((a,b)=>Math.abs(a.totalCards-admin.actualCards)-Math.abs(b.totalCards-admin.actualCards)||a.submittedAt.localeCompare(b.submittedAt))[0];
  return <main className="space-y-4"><section className="card space-y-2"><h2 className="text-xl font-semibold">Admin Controls</h2><button className="px-3 py-1 rounded bg-brand-navy text-white" onClick={()=>setAdmin({...admin, locked: !admin.locked})}>{admin.locked?'Unlock Entries':'Lock Entries'}</button><div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><label className="text-sm">Actual total goals <input type="number" className="border rounded p-1 w-full" value={admin.actualGoals} onChange={(e)=>setAdmin({...admin, actualGoals:Number(e.target.value)})}/></label><label className="text-sm">Actual total booking cards <input type="number" className="border rounded p-1 w-full" value={admin.actualCards} onChange={(e)=>setAdmin({...admin, actualCards:Number(e.target.value)})}/></label></div></section><section className="card"><h3 className="font-semibold mb-2">Teams</h3><div className="grid grid-cols-2 sm:grid-cols-3 gap-2">{admin.teams.map((team)=> <button key={team.name} className={`p-2 text-sm rounded border ${team.status==='active'?'bg-emerald-50':'bg-rose-50'}`} onClick={()=>setAdmin({...admin, teams:admin.teams.map(t=>t.name===team.name?{...t,status:t.status==='active'?'eliminated':'active'}:t)})}>{team.name} ({team.status})</button>)}</div></section><section className="card"><h3 className="font-semibold mb-2">Current category leaders</h3><ul className="text-sm space-y-1"><li>Winner category: most entries shown on leaderboard.</li><li>Total goals leader: {winnerGoals?winnerGoals.fullName:'N/A'}</li><li>Total booking cards leader: {winnerCards?winnerCards.fullName:'N/A'}</li></ul></section><section className="card"><h3 className="font-semibold mb-2">All Predictions</h3><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th>Name</th><th>Email</th><th>Winner</th><th>Goals</th><th>Cards</th></tr></thead><tbody>{predictions.map(p=><tr key={p.id} className="border-b"><td>{p.fullName}</td><td>{p.email}</td><td>{p.winner}</td><td>{p.totalGoals}</td><td>{p.totalCards}</td></tr>)}</tbody></table></div></section></main>;
}
